import { writeFileSync } from "node:fs";
import { assertContentValid } from "../content/index";

/**
 * Generates public/admin/data.js from the content layer.
 *
 * The dashboard's dropdowns — doctors, cities, quartiers, tariffs — must be
 * the same values the public site publishes. Hardcoding them in the admin
 * HTML would mean a doctor could leave the site and linger in the dispatch
 * form, or a tariff could change on /tarifs and not in the cash ledger. Both
 * are the kind of drift nobody notices until the numbers disagree.
 *
 * Runs in `prebuild`, so the file cannot be stale.
 */
const content = assertContentValid();

const data = {
  doctors: content.doctors.map((d) => ({
    slug: d.slug,
    name: d.name,
    specialty: content.specialties.find((s) => s.slug === d.specialtySlug)?.name ?? d.specialtySlug,
  })),
  cities: content.cities.map((c) => ({ slug: c.slug, name: c.name })),
  quartiers: content.quartiers.map((q) => ({ slug: q.slug, name: q.name, city: q.citySlug })),
  tariffs: content.pricing.tiers.map((t) => ({
    slug: t.slug,
    label: t.label,
    amount: Number(t.amountMad),
    // The doctor keeps this; the remainder is what he owes the company.
    doctorShare: Number(t.doctorShareMad),
    companyShare: Number(t.amountMad) - Number(t.doctorShareMad),
    window: t.window,
  })),
  currency: content.pricing.currency,
  situations: content.situations.map((s) => ({ slug: s.slug, title: s.title })),
};

writeFileSync(
  "public/admin/data.js",
  `// GENERATED by scripts/gen-admin-data.ts — do not edit.\n` +
    `// Regenerated on every build from the content layer, so the dispatch form\n` +
    `// can never offer a doctor, city or tariff the public site does not have.\n` +
    `export const DATA = ${JSON.stringify(data, null, 2)};\n`,
  "utf8"
);

console.log(
  `admin-data: ${data.doctors.length} doctors, ${data.cities.length} cities, ` +
    `${data.quartiers.length} quartiers, ${data.tariffs.length} tariffs`
);
